WIP: Add scale parameter to blackbody emitter
mitsuba-renderer/mitsuba2 pull request #406
Opened 2021-03-31 02:02 UTC by alhirzel

*Please add the labels (e.g. bug, feature, ..) corresponding to this PR*

## Description

This PR adds the `scale` parameter back to the `blackbody` emitter.
This feature is useful when scenes are not expressed in meters, or when simulating a gray body.

## Testing

*Please describe the tests that you added to verify your changes.*

## Checklist:

*Please make sure to complete this checklist before requesting a review.*

- [x] My code follows the [style guidelines](https://mitsuba2.readthedocs.io/en/latest/src/developer_guide/intro.html#introduction) of this project
- [x] My changes generate no new warnings
- [ ] My code also compiles for `gpu_*` and `packet_*` variants. If you can't test this, please leave below
- [x] I have commented my code
- [x] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I cleaned the commit history and removed any "Merge" commits
- [x] I give permission that the Mitsuba 2 project may redistribute my contributions under the terms of its [license](https://github.com/mitsuba-renderer/mitsuba2/blob/master/LICENSE)

2021-04-24 19:45 UTC, alhirzel commented
I removed WIP but haven't run the tests formally yet. What level of test would be expected for this change?

2021-04-26 07:20 UTC, Speierers requested changes
Hi @alhirzel ,

Thanks for this PR. Please take a look at the two comments I left above.

Regarding testing, it would be great to add a chi2 test to check that this spectrum remains "valid" after scaling.

Also, should we make sure `m_scale` is always a positive value? Always greater than zero? Maybe you could throw an error in the constructor is this is not the case.

Actually, you might need to check for this in `parameters_changed()` as well in case someone sets a negative value using the `traverse` mechanism.

2021-04-26 07:20 UTC, Speierers commented on src/spectra/blackbody.cpp
> +            m_scale = 1.f;
You should use `props.float_("scale", 1.f)` here instead of the `if .. else ..` statement

2021-04-26 07:20 UTC, Speierers commented on src/spectra/blackbody.cpp
> +            Wavelength pdf = 1e-9f * m_scale * c0 * exp(-c1 / (lambda * m_temperature))
Do we really need to scale the PDF here? I think those values should be "normalized" no? Is this how it is implemented in Mitsuba 0.6?

2022-10-03 18:23 UTC, closed without merging